version: '3.3'

volumes:
  pgdata-app:

services:

  internship-process:
    container_name: internship_db
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata-app:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: internship_db
